### PR TITLE
Add zh_cn localization

### PR DESCRIPTION
**Pull request by RawPineapple**
Added Simplified Chinese localization

### CODE REVIEW

**Comment by NinjaPhenix** [comment]
Thank you, will review in a little bit and port to older versions as needed.

**Comment by NinjaPhenix** [comment]
Are you fine with these being published under 0-bsd license ( the one that all other localization files are under)?

**Comment by RawPineapple** [comment]
> Are you fine with these being published under 0-bsd license ( the one that all other localization files are under)?

Yep, I’m ok with that.

**Comment by NinjaPhenix** [comment]
Thanks for the contribution, will try and get a build out tomorrow ( currently working on 1.16.5 )

**Pull request merged**
